// Generated by https://quicktype.io

export interface ActivitiesResponse {
    activities: Activity[];
}

export interface Activity {
    resource_state:                number;
    athlete:                       Athlete;
    name:                          string;
    distance:                      number;
    moving_time:                   number;
    elapsed_time:                  number;
    total_elevation_gain:          number;
    type:                          string;
    workout_type?:                 number;
    id:                            number;
    external_id:                   string;
    upload_id:                     number;
    start_date:                    string;
    start_date_local:              string;
    timezone:                      string;
    utc_offset:                    number;
    start_latlng:                  number[];
    end_latlng:                    number[];
    location_city:                 null;
    location_state:                null;
    location_country:              null;
    start_latitude:                number | null;
    start_longitude:               number | null;
    achievement_count:             number;
    kudos_count:                   number;
    comment_count:                 number;
    athlete_count:                 number;
    photo_count:                   number;
    map:                           Map;
    trainer:                       boolean;
    commute:                       boolean;
    manual:                        boolean;
    private:                       boolean;
    visibility:                    string;
    flagged:                       boolean;
    gear_id:                       null;
    from_accepted_tag:             boolean;
    upload_id_str:                 string;
    average_speed:                 number;
    max_speed:                     number;
    has_heartrate:                 boolean;
    heartrate_opt_out:             boolean;
    display_hide_heartrate_option: boolean;
    elev_high?:                    number;
    elev_low?:                     number;
    pr_count:                      number;
    total_photo_count:             number;
    has_kudoed:                    boolean;
}

export interface Athlete {
    id:             number;
    resource_state: number;
}

export interface Map {
    id:               string;
    summary_polyline: null | string;
    resource_state:   number;
}
